"""P6-06 freeze verification. Generates and inspects real PDF/DOCX. Does not change engines."""

from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

from docx import Document
from playwright.sync_api import sync_playwright

from engines.date_selection.service import DateSelectionService
from engines.date_selection_report import (
    DateSelectionReportAdapter,
    build_render_tree,
    create_render_context,
    export_docx,
    export_pdf,
)
from engines.date_selection_report.exporting.docx_exporter import extract_docx_text
from engines.date_selection_report.rendering.labels import LABELS

ROOT = Path(__file__).resolve().parent
SHOTS = ROOT / "screenshots"
PORTAL = "http://127.0.0.1:8081"

REQUIRED_LABELS = (
    LABELS["report_title"],
    "Tóm tắt",
    LABELS["section_person"],
    LABELS["section_search"],
    LABELS["section_recommendations"],
    LABELS["compatible_hours"],
    LABELS["positive_times"],
    LABELS["section_guidance"],
    LABELS["footer_product"],
    "BTE Platform",
    "Nguyễn Tiến Sơn",
)

PDF_REQUIRED_LABELS = (
    LABELS["report_title"],
    "Khách hàng",
    LABELS["section_person"],
    LABELS["section_search"],
    LABELS["section_recommendations"],
    LABELS["compatible_hours"],
    LABELS["positive_times"],
    LABELS["section_guidance"],
    "Generated by BTE Platform",
    "Nguyễn Tiến Sơn",
)

NAMED_STYLES = (
    "ReportTitle",
    "SectionTitle",
    "RecommendationTitle",
    "Result",
    "Label",
    "Value",
    "Caption",
    "Footer",
)


def _search():
    return DateSelectionService().search(
        full_name="Nguyễn Tiến Sơn",
        gender="male",
        birth_year=1987,
        birth_month=1,
        birth_day=21,
        target_year=2026,
        target_month=9,
    )


def _order(result) -> list[str]:
    return [item.day.calendar.solar_label for item in result.dates]


def _assert_contains(text: str, label: str, where: str) -> None:
    compact_text = "".join(text.split())
    compact_label = "".join(label.split())
    if label in text or compact_label in compact_text:
        return
    raise SystemExit(f"{where} missing {label!r}")


def _assert_order(text: str, solar_labels: list[str]) -> None:
    compact = "".join(text.split())
    positions = []
    for label in solar_labels:
        compact_label = "".join(label.split())
        pos = text.find(label)
        if pos < 0:
            pos = compact.find(compact_label)
        positions.append(pos)
    if any(pos < 0 for pos in positions):
        missing = [label for label, pos in zip(solar_labels, positions) if pos < 0]
        raise SystemExit(f"missing solar labels: {missing}")
    if positions != sorted(positions):
        raise SystemExit(f"recommendation order mismatch: {solar_labels} at {positions}")


def _screenshot_pdf(pdf_path: Path) -> tuple[int, str]:
    SHOTS.mkdir(parents=True, exist_ok=True)
    viewer = ROOT / "_pdf_viewer.html"
    b64 = __import__("base64").b64encode(pdf_path.read_bytes()).decode("ascii")
    viewer.write_text(
        f"""<!doctype html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;background:#525659">
<div id="pages"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
<script>
pdfjsLib.GlobalWorkerOptions.workerSrc =
  "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const bytes = Uint8Array.from(atob("{b64}"), c => c.charCodeAt(0));
(async () => {{
  const pdf = await pdfjsLib.getDocument({{ data: bytes }}).promise;
  window.__pageCount = pdf.numPages;
  const host = document.getElementById("pages");
  const texts = [];
  for (let i = 1; i <= pdf.numPages; i++) {{
    const page = await pdf.getPage(i);
    const viewport = page.getViewport({{ scale: 1.35 }});
    const canvas = document.createElement("canvas");
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    canvas.style.display = "block";
    canvas.style.margin = "0 auto 16px";
    host.appendChild(canvas);
    await page.render({{ canvasContext: canvas.getContext("2d"), viewport }}).promise;
    const content = await page.getTextContent();
    texts.push(content.items.map(item => item.str).join(" "));
  }}
  window.__pdfText = texts.join("\\n");
  window.__ready = true;
}})();
</script>
</body></html>
""",
        encoding="utf-8",
    )
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        page = browser.new_page(viewport={"width": 900, "height": 1200})
        page.goto(viewer.as_uri(), wait_until="networkidle", timeout=60000)
        page.wait_for_function("() => window.__ready === true", timeout=60000)
        count = int(page.evaluate("window.__pageCount"))
        pdf_text = str(page.evaluate("window.__pdfText") or "")
        canvases = page.locator("#pages canvas")
        n = canvases.count()
        for index in range(n):
            canvases.nth(index).screenshot(path=str(SHOTS / f"pdf_page_{index + 1:02d}.png"))
        browser.close()
    viewer.unlink(missing_ok=True)
    return count, pdf_text


def _word_open(docx_path: Path) -> dict:
    import subprocess

    ps1 = ROOT / "_open_word.ps1"
    ps1.write_text(
        "\n".join(
            [
                "$ErrorActionPreference = 'Stop'",
                f"$path = {json.dumps(str(docx_path.resolve()))}",
                "$word = New-Object -ComObject Word.Application",
                "$word.Visible = $false",
                "$word.DisplayAlerts = 0",
                "try {",
                "  $doc = $word.Documents.Open($path, $false, $false)",
                "  $payload = @{",
                "    read_only = [bool]$doc.ReadOnly",
                "    protection = [int]$doc.ProtectionType",
                "    paragraphs = [int]$doc.Paragraphs.Count",
                "    windows = [int]$doc.Windows.Count",
                "  }",
                "  $doc.Close($false)",
                "  $payload | ConvertTo-Json -Compress",
                "} finally {",
                "  $word.Quit() | Out-Null",
                "}",
            ]
        ),
        encoding="utf-8",
    )
    completed = subprocess.run(
        [
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(ps1),
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    ps1.unlink(missing_ok=True)
    if completed.returncode != 0:
        raise SystemExit(f"Word COM failed: {completed.stderr or completed.stdout}")
    return json.loads(completed.stdout.strip())


def _portal_export() -> tuple[Path, Path]:
    out = ROOT / "browser"
    out.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        page = browser.new_page(viewport={"width": 1440, "height": 1100})
        errors: list[str] = []
        page.on("pageerror", lambda err: errors.append(str(err)))
        page.goto(f"{PORTAL}/choose-date", wait_until="networkidle", timeout=60000)
        page.fill("#dsFullName", "Nguyễn Tiến Sơn")
        page.check("input[name=gender][value=male]")
        page.fill("#dsBirth", "21/01/1987")
        page.fill("#dsTargetMonth", "09/2026")
        page.click("#dsSearchBtn")
        page.wait_for_selector("[data-testid=ranked-card]", timeout=30000)
        cards = page.locator("[data-testid=ranked-card]").count()
        if cards < 1:
            raise SystemExit("portal search produced no Top-5 cards")
        page.wait_for_selector("#dsExport:not([hidden])", timeout=5000)
        with page.expect_download(timeout=120000) as pdf_info:
            page.click("#dsExportPdf")
        pdf = pdf_info.value
        pdf_path = out / (pdf.suggested_filename or "export.pdf")
        pdf.save_as(str(pdf_path))
        page.wait_for_function(
            "() => !document.getElementById('dsExportPdf')?.disabled",
            timeout=10000,
        )
        with page.expect_download(timeout=120000) as docx_info:
            page.click("#dsExportDocx")
        docx = docx_info.value
        docx_path = out / (docx.suggested_filename or "export.docx")
        docx.save_as(str(docx_path))
        status = page.locator("#dsExportStatus")
        visible_error = status.is_visible() and (status.inner_text() or "").strip()
        browser.close()
        if errors:
            raise SystemExit(f"portal pageerror: {errors}")
        if visible_error:
            raise SystemExit(f"portal export status error: {visible_error}")
        if cards < 1:
            raise SystemExit("no ranked cards")
        print("portal_top5_cards", cards)
        return pdf_path, docx_path


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    result = _search()
    solar = _order(result)
    payload = result.to_dict()
    (ROOT / "search.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    model = DateSelectionReportAdapter().adapt(result)
    tree = build_render_tree(create_render_context(model))
    pdf_result = export_pdf(tree, ROOT)
    docx_result = export_docx(tree, ROOT)
    pdf_path = Path(pdf_result.file_path)
    docx_path = Path(docx_result.file_path)
    if pdf_path.read_bytes()[:5] != b"%PDF-":
        raise SystemExit("PDF magic mismatch")
    if docx_path.read_bytes()[:2] != b"PK":
        raise SystemExit("DOCX magic mismatch")

    text = extract_docx_text(docx_path)
    for label in REQUIRED_LABELS:
        _assert_contains(text, label, "DOCX")
    _assert_order(text, solar)
    document = Document(str(docx_path))
    style_names = {style.name for style in document.styles}
    missing_styles = [name for name in NAMED_STYLES if name not in style_names]
    if missing_styles:
        raise SystemExit(f"DOCX missing styles: {missing_styles}")
    xml = zipfile.ZipFile(io.BytesIO(docx_path.read_bytes())).read("word/document.xml").decode("utf-8")
    if "eastAsia" not in xml and "w:eastAsia" not in zipfile.ZipFile(
        io.BytesIO(docx_path.read_bytes())
    ).read("word/styles.xml").decode("utf-8"):
        styles_xml = zipfile.ZipFile(io.BytesIO(docx_path.read_bytes())).read("word/styles.xml").decode(
            "utf-8"
        )
        if "eastAsia" not in styles_xml:
            raise SystemExit("DOCX missing eastAsia Unicode font hint")
    if "Nguyễn Tiến Sơn" not in xml:
        raise SystemExit("DOCX XML missing Unicode name")

    word_info = _word_open(docx_path)
    if word_info["read_only"]:
        raise SystemExit("Word opened DOCX as read-only")
    if word_info["protection"] not in (-1, 0):
        raise SystemExit(f"Word document is protected: {word_info}")

    page_count, pdf_text = _screenshot_pdf(pdf_path)
    if page_count < 2:
        raise SystemExit(f"PDF page count too low: {page_count}")
    for label in PDF_REQUIRED_LABELS:
        _assert_contains(pdf_text, label, "PDF")
    _assert_order(pdf_text, solar)
    (ROOT / "pdf_text.txt").write_text(pdf_text, encoding="utf-8")

    portal_pdf, portal_docx = _portal_export()
    if portal_pdf.read_bytes()[:5] != b"%PDF-":
        raise SystemExit("portal PDF magic mismatch")
    if portal_docx.read_bytes()[:2] != b"PK":
        raise SystemExit("portal DOCX magic mismatch")
    portal_text = extract_docx_text(portal_docx)
    for label in REQUIRED_LABELS:
        _assert_contains(portal_text, label, "portal DOCX")
    _assert_order(portal_text, solar)

    summary = {
        "sample": "Nguyễn Tiến Sơn / Nam / 21/01/1987 / 09/2026",
        "recommendations": solar,
        "pdf": {
            "path": str(pdf_path),
            "size": pdf_path.stat().st_size,
            "pages": page_count,
            "unicode_ok": "Nguyễn Tiến Sơn" in pdf_text,
        },
        "docx": {
            "path": str(docx_path),
            "size": docx_path.stat().st_size,
            "word": word_info,
            "styles": list(NAMED_STYLES),
        },
        "portal": {
            "pdf": str(portal_pdf),
            "pdf_size": portal_pdf.stat().st_size,
            "docx": str(portal_docx),
            "docx_size": portal_docx.stat().st_size,
        },
        "required_labels": list(REQUIRED_LABELS),
    }
    (ROOT / "freeze_verify.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
