"""CK-01B frozen Consulting Knowledge Catalog. Entries only. No matching."""

from __future__ import annotations

from typing import Any, Mapping

from engines.consulting_knowledge.models import ConsultingKnowledgeUnit

_STRENGTH_STRONG = "Thân vượng"
_STRENGTH_WEAK = "Thân nhược"
_ACTION_PREFIX = "consulting_knowledge.action_library"


def _unit(
    unit_id: str,
    domain: str,
    condition: Mapping[str, Any],
    meaning: str,
    wording: str,
    action: str,
    *references: str,
    action_id: str | None = None,
) -> ConsultingKnowledgeUnit:
    """Build one stored catalog unit. Does not match signals."""
    refs = list(references)
    if action_id is not None:
        refs.append(f"{_ACTION_PREFIX}.{action_id}")
    return ConsultingKnowledgeUnit(
        unit_id=unit_id,
        domain=domain,
        condition=dict(condition),
        applicable_scope={"domain": domain, "audience": "customer"},
        consulting_meaning=meaning,
        customer_wording=(wording,),
        recommended_actions=(action,),
        references=tuple(refs),
        status="complete",
    )


CONSULTING_KNOWLEDGE_CATALOG: tuple[ConsultingKnowledgeUnit, ...] = (
    _unit(
        "ck-career-001",
        "career",
        {"strength_level": _STRENGTH_STRONG},
        "Sức gánh cao dễ biến thành việc nặng mà không đúng việc.",
        "Ưu tiên dựng khung việc trước khi mở rộng.",
        "Dựng khung vừa đủ để việc chạy.",
        "analysis.strength.strength_level",
        action_id="ck-action-001",
    ),
    _unit(
        "ck-career-002",
        "career",
        {"strength_level": _STRENGTH_WEAK},
        "Sức gánh thấp cần điểm tựa, không cần thêm vai.",
        "Đừng ôm hết việc. Chọn một điểm tựa rõ trước khi nhận thêm trách nhiệm.",
        "Chọn một người được phép chỉnh phương pháp.",
        "analysis.strength.strength_level",
        action_id="ck-action-003",
    ),
    _unit(
        "ck-finance-001",
        "finance",
        {"strength_level": _STRENGTH_STRONG},
        "Dòng tiền có thể bị kéo căng khi việc mở quá nhanh.",
        "Khóa một khung chi trước khi mở thêm cam kết.",
        "Dựng khung vừa đủ để việc chạy.",
        "analysis.strength.strength_level",
        action_id="ck-action-001",
    ),
    _unit(
        "ck-finance-002",
        "finance",
        {"strength_level": _STRENGTH_WEAK},
        "Nguồn lực cần được giữ tập trung trước khi mở kênh mới.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "analysis.strength.strength_level",
        action_id="ck-action-004",
    ),
    _unit(
        "ck-relationship-001",
        "relationship",
        {"strength_level": _STRENGTH_STRONG},
        "Thế chủ động dễ biến thành chỉ đạo khi đối phương cần được nghe.",
        "Rút ngắn chỉ dẫn. Để chỗ cho người kia nói trước khi chốt.",
        "Chọn một người được phép chỉnh phương pháp.",
        "analysis.strength.strength_level",
        action_id="ck-action-003",
    ),
    _unit(
        "ck-relationship-002",
        "relationship",
        {"strength_level": _STRENGTH_WEAK},
        "Thế cần điểm tựa dễ biến thành im lặng khi việc cần được nói rõ.",
        "Đặt tên một người được chia tải, thay vì gánh một mình.",
        "Chọn một người được phép chỉnh phương pháp.",
        "analysis.strength.strength_level",
        action_id="ck-action-003",
    ),
    _unit(
        "ck-health-001",
        "health",
        {"strength_level": _STRENGTH_STRONG},
        "Chịu tải cao dễ đẩy nghỉ ra khỏi lịch cho đến khi kiệt.",
        "Đặt nghỉ vào lịch trước khi mở thêm việc. Đây là nhịp vận hành, không phải chẩn đoán.",
        "Đặt nghỉ vào lịch trước khi mở thêm việc.",
        "analysis.strength.strength_level",
        action_id="ck-action-002",
    ),
    _unit(
        "ck-health-002",
        "health",
        {"strength_level": _STRENGTH_WEAK},
        "Thế cần điểm tựa dễ mất cửa sổ phục hồi khi nhận thêm tải.",
        "Giữ cửa sổ nghỉ đã đặt. Đừng lấy chỗ đó để nhận việc mới.",
        "Đặt nghỉ vào lịch trước khi mở thêm việc.",
        "analysis.strength.strength_level",
        action_id="ck-action-002",
    ),
    _unit(
        "ck-leadership-001",
        "leadership",
        {"useful_god": "Chính Quan"},
        "Dụng thần Chính Quan đã công bố nghiêng về khung trách nhiệm rõ, không phải sức hút cá nhân.",
        "Dẫn bằng vai trò và ranh giới. Đừng thay khung bằng việc làm thay.",
        "Dựng khung vừa đủ để việc chạy.",
        "analysis.useful_god.useful_god",
        action_id="ck-action-001",
    ),
    _unit(
        "ck-leadership-002",
        "leadership",
        {"strength_level": _STRENGTH_STRONG},
        "Sức gánh cao dễ biến lãnh đạo thành người làm hết việc của đội.",
        "Giao việc kèm quyền chỉnh phương pháp. Giữ khung, không giữ hết tay.",
        "Chọn một người được phép chỉnh phương pháp.",
        "analysis.strength.strength_level",
        action_id="ck-action-003",
    ),
    _unit(
        "ck-management-001",
        "management",
        {"strength_level": _STRENGTH_STRONG},
        "Thế chịu tải cao dễ chồng thêm quy trình khi việc chỉ cần một khung.",
        "Giữ một nhịp vận hành. Mở quy trình mới chỉ khi khung hiện tại đã chạy.",
        "Dựng khung vừa đủ để việc chạy.",
        "analysis.strength.strength_level",
        action_id="ck-action-001",
    ),
    _unit(
        "ck-management-002",
        "management",
        {"strength_level": _STRENGTH_WEAK},
        "Thế cần điểm tựa dễ mất nhịp khi đội chạy nhiều hệ song song.",
        "Chọn một nhịp chính. Đừng mở hệ thứ hai trước khi hệ thứ nhất đứng được.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "analysis.strength.strength_level",
        action_id="ck-action-004",
    ),
    _unit(
        "ck-communication-001",
        "communication",
        {"strength_level": _STRENGTH_STRONG},
        "Thế chủ động dễ làm thông điệp át chỗ người khác cần hiểu.",
        "Rút ngắn thông điệp. Chốt một việc cần người kia nắm trước khi thêm ý.",
        "Dựng khung vừa đủ để việc chạy.",
        "analysis.strength.strength_level",
        action_id="ck-action-001",
    ),
    _unit(
        "ck-communication-002",
        "communication",
        {"strength_level": _STRENGTH_WEAK},
        "Thế cần điểm tựa dễ để việc quan trọng không được nói đủ rõ.",
        "Viết một ý chính trước khi vào cuộc họp quan trọng.",
        "Dựng khung vừa đủ để việc chạy.",
        "analysis.strength.strength_level",
        action_id="ck-action-001",
    ),
    _unit(
        "ck-business-001",
        "business",
        {"strength_level": _STRENGTH_STRONG},
        "Sức mở cao dễ kéo doanh nghiệp ra nhiều mặt trận cùng lúc.",
        "Chọn một hướng chính. Đừng mở ba mặt trận trước khi mặt trận một đứng được.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "analysis.strength.strength_level",
        action_id="ck-action-004",
    ),
    _unit(
        "ck-business-002",
        "business",
        {"strength_level": _STRENGTH_WEAK},
        "Nguồn lực mỏng cần một cửa vào việc, không cần thêm sản phẩm.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "analysis.strength.strength_level",
        action_id="ck-action-004",
    ),
    _unit(
        "ck-personality-001",
        "personality",
        {"strength_level": _STRENGTH_STRONG},
        "Nhịp chủ động mạnh cần một phanh đã đặt sẵn, không phải thêm tốc độ.",
        "Giữ sức đẩy. Ghép một điểm dừng đã hẹn trên lịch.",
        "Đặt nghỉ vào lịch trước khi mở thêm việc.",
        "analysis.strength.strength_level",
        action_id="ck-action-002",
    ),
    _unit(
        "ck-personality-002",
        "personality",
        {"strength_level": _STRENGTH_WEAK},
        "Nhịp thận trọng cần một đồng minh đã đặt tên, không phải thêm gánh.",
        "Giữ sự cẩn trọng. Đặt tên một người được chia việc khó.",
        "Chọn một người được phép chỉnh phương pháp.",
        "analysis.strength.strength_level",
        action_id="ck-action-003",
    ),
    _unit(
        "ck-action-001",
        "action_library",
        {"action_kind": "operating_frame"},
        "Hành động tái sử dụng: dựng khung vừa đủ trước khi mở rộng.",
        "Dựng khung vừa đủ để việc chạy.",
        "Dựng khung vừa đủ để việc chạy.",
        f"{_ACTION_PREFIX}.ck-action-001",
    ),
    _unit(
        "ck-action-002",
        "action_library",
        {"action_kind": "rest_on_calendar"},
        "Hành động tái sử dụng: nghỉ được đặt trên lịch, không để đến lúc kiệt.",
        "Đặt nghỉ vào lịch trước khi mở thêm việc.",
        "Đặt nghỉ vào lịch trước khi mở thêm việc.",
        f"{_ACTION_PREFIX}.ck-action-002",
    ),
    _unit(
        "ck-action-003",
        "action_library",
        {"action_kind": "named_ally"},
        "Hành động tái sử dụng: một người được phép chỉnh phương pháp.",
        "Chọn một người được phép chỉnh phương pháp.",
        "Chọn một người được phép chỉnh phương pháp.",
        f"{_ACTION_PREFIX}.ck-action-003",
    ),
    _unit(
        "ck-action-004",
        "action_library",
        {"action_kind": "one_channel"},
        "Hành động tái sử dụng: một kênh chính trước khi mở kênh mới.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        "Giữ một kênh chính trước khi mở kênh mới.",
        f"{_ACTION_PREFIX}.ck-action-004",
    ),
)
