proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=bte_static:10m max_size=100m inactive=60m use_temp_path=off;

map $sent_http_content_type $bte_cacheable {
    default                 0;
    ~*text/css              1;
    ~*javascript            1;
    ~*image/                1;
    ~*font/                 1;
}
