"""Analysis Engine shared type system."""

from __future__ import annotations

from engines.analysis_engine.types.categories import (
    AnalysisCategory,
    CategoryId,
    CategoryLiteral,
    CategoryPayload,
)
from engines.analysis_engine.types.confidence import (
    ConfidenceBand,
    ConfidencePayload,
    ConfidencePercent,
    ConfidenceValue,
)
from engines.analysis_engine.types.enums import DecisionOutcome, ObjectType, ResultKind
from engines.analysis_engine.types.ids import (
    AnalyzerId,
    ChartId,
    ContextId,
    ContextIdNT,
    DecisionId,
    EvidenceId,
    ExecutionId,
    ModuleId,
    PackId,
    PipelineId,
    PipelineIdNT,
    ReferenceId,
    RegistryEntryId,
    RegistryEntryIdNT,
    ResultId,
    ResultIdNT,
    RuleId,
    SchemaId,
    ScoreId,
    SnapshotId,
    StageId,
    StageIdNT,
    TraceId,
)
from engines.analysis_engine.types.priority import (
    PriorityLevel,
    PriorityLiteral,
    PriorityPayload,
    PriorityValue,
)
from engines.analysis_engine.types.severity import Severity, SeverityLiteral, SeverityPayload
from engines.analysis_engine.types.status import (
    ExecutionStatus,
    LifecycleStatus,
    StatusLiteral,
    StatusPayload,
)
from engines.analysis_engine.types.versions import (
    CompatibilityMode,
    EngineVersion,
    ModuleVersion,
    SchemaVersion,
    VersionKind,
    VersionParts,
    VersionRef,
    VersionString,
)
from engines.analysis_engine.types.weights import (
    NormalizedWeight,
    WeightPayload,
    WeightUnit,
    WeightValue,
)

__all__ = [
    "AnalysisCategory",
    "AnalyzerId",
    "CategoryId",
    "CategoryLiteral",
    "CategoryPayload",
    "ChartId",
    "CompatibilityMode",
    "ConfidenceBand",
    "ConfidencePayload",
    "ConfidencePercent",
    "ConfidenceValue",
    "ContextId",
    "ContextIdNT",
    "DecisionId",
    "DecisionOutcome",
    "EngineVersion",
    "EvidenceId",
    "ExecutionId",
    "ExecutionStatus",
    "LifecycleStatus",
    "ModuleId",
    "ModuleVersion",
    "NormalizedWeight",
    "ObjectType",
    "PackId",
    "PipelineId",
    "PipelineIdNT",
    "PriorityLevel",
    "PriorityLiteral",
    "PriorityPayload",
    "PriorityValue",
    "ReferenceId",
    "RegistryEntryId",
    "RegistryEntryIdNT",
    "ResultId",
    "ResultIdNT",
    "ResultKind",
    "RuleId",
    "SchemaId",
    "SchemaVersion",
    "ScoreId",
    "Severity",
    "SeverityLiteral",
    "SeverityPayload",
    "SnapshotId",
    "StageId",
    "StageIdNT",
    "StatusLiteral",
    "StatusPayload",
    "TraceId",
    "VersionKind",
    "VersionParts",
    "VersionRef",
    "VersionString",
    "WeightPayload",
    "WeightUnit",
    "WeightValue",
]
