/**
 * Print chrome labels. Not Narrative. Not astrology meaning.
 */

export const PRINT_GENERATED_BY = "Generated by BTE";

export const PRINT_CONFIDENTIAL = "Confidential";

export const PRINT_PREPARED_BY = "Prepared by";

export const PRINT_PREPARED_ORG = "BTE Platform";
