/**
 * Running print footer. Page marker, Generated by BTE, version, confidential.
 */

import type { ReactNode } from "react";
import { PRINT_CONFIDENTIAL, PRINT_GENERATED_BY } from "./copy";

type PrintFooterProps = {
  readonly version: string;
};

/**
 * Repeating footer for print pages. Hidden on screen. No engine or rule ids.
 */
export function PrintFooter({ version }: PrintFooterProps): ReactNode {
  return (
    <footer className="bte-print__footer" data-print="footer">
      <span className="bte-print__footer-gen">{PRINT_GENERATED_BY}</span>
      {version ? <span className="bte-print__footer-version">{version}</span> : null}
      <span className="bte-print__footer-conf">{PRINT_CONFIDENTIAL}</span>
      <span className="bte-print__page" data-print="page-number" />
    </footer>
  );
}
