"""Pack 07 Detailed Interpretation Engine — public API.

Exports Service, Engine, and Models only. No interpretation algorithms.
"""

from __future__ import annotations

from engines.detailed_interpretation_engine.builders import (
    CanonicalAnalysisContextBuilder,
    DomainContextBuilder,
    EvidenceContextBuilder,
    InterpretationContextBuilder,
    NarrativeContextBuilder,
    OptimizationContextBuilder,
    TemporalContextBuilder,
)
from engines.detailed_interpretation_engine.diagnostics import (
    Pack07RuntimeDiagnostics,
    build_pack07_diagnostics,
)
from engines.detailed_interpretation_engine.engine import DetailedInterpretationEngine
from engines.detailed_interpretation_engine.factories import (
    build_canonical_analysis_context,
    build_domain_context,
    build_evidence_context,
    build_interpretation_context,
    build_narrative_context,
    build_optimization_context,
    build_temporal_context,
)
from engines.detailed_interpretation_engine.models import (
    AuthorityResult,
    CanonicalAPIModel,
    CanonicalAnalysisContext,
    CanonicalAnalysisResult,
    CanonicalConsultingModel,
    CanonicalExportModel,
    CanonicalRuntimeResult,
    CareerResult,
    ChartIdentity,
    ConfidenceValue,
    DomainContext,
    DomainInterpretationResult,
    EvidenceContext,
    EvidencePriorityResult,
    InterpretationContext,
    LegacyResult,
    LifeOptimizationResult,
    NarrativeContext,
    NarrativeGraph,
    NarrativeResult,
    OptimizationContext,
    OptimizationResult,
    RelationshipResult,
    RuntimeMetadata,
    ShenShaEcosystem,
    TemporalActivationResult,
    TemporalContext,
    TenGodEcosystem,
    TraceRef,
    VersionBundle,
    VitalityResult,
    WealthResult,
)
from engines.detailed_interpretation_engine.schema_registry import (
    PACK07_SCHEMA_REGISTRY,
    register_pack07_schemas,
    registered_schema_ids,
)
from engines.detailed_interpretation_engine.service import DetailedInterpretationService
from engines.detailed_interpretation_engine.validation import ValidationIssue, ValidationResult
from engines.detailed_interpretation_engine.validators import (
    validate_api_projection,
    validate_canonical_runtime,
    validate_consulting_projection,
    validate_export_projection,
    validate_pack07_context,
)

__all__ = [
    "AuthorityResult",
    "CanonicalAPIModel",
    "CanonicalAnalysisContext",
    "CanonicalAnalysisContextBuilder",
    "CanonicalAnalysisResult",
    "CanonicalConsultingModel",
    "CanonicalExportModel",
    "CanonicalRuntimeResult",
    "CareerResult",
    "ChartIdentity",
    "ConfidenceValue",
    "DetailedInterpretationEngine",
    "DetailedInterpretationService",
    "DomainContext",
    "DomainContextBuilder",
    "DomainInterpretationResult",
    "EvidenceContext",
    "EvidenceContextBuilder",
    "EvidencePriorityResult",
    "InterpretationContext",
    "InterpretationContextBuilder",
    "LegacyResult",
    "LifeOptimizationResult",
    "NarrativeContext",
    "NarrativeContextBuilder",
    "NarrativeGraph",
    "NarrativeResult",
    "OptimizationContext",
    "OptimizationContextBuilder",
    "OptimizationResult",
    "PACK07_SCHEMA_REGISTRY",
    "Pack07RuntimeDiagnostics",
    "RelationshipResult",
    "RuntimeMetadata",
    "ShenShaEcosystem",
    "TemporalActivationResult",
    "TemporalContext",
    "TemporalContextBuilder",
    "TenGodEcosystem",
    "TraceRef",
    "VersionBundle",
    "VitalityResult",
    "WealthResult",
    "ValidationIssue",
    "ValidationResult",
    "build_canonical_analysis_context",
    "build_domain_context",
    "build_evidence_context",
    "build_interpretation_context",
    "build_narrative_context",
    "build_optimization_context",
    "build_temporal_context",
    "build_pack07_diagnostics",
    "register_pack07_schemas",
    "registered_schema_ids",
    "validate_api_projection",
    "validate_canonical_runtime",
    "validate_consulting_projection",
    "validate_export_projection",
    "validate_pack07_context",
]
