"""
Luck Engine
===========

Standalone runtime engine producing ``LuckContext``.

Public API
----------
LuckEngine
LuckContext
Provider / evaluator protocols
Default providers and layered Dayun/Liunian evaluators
"""

from .context import LuckContext
from .engine import LuckEngine
from .evaluation_models import (
    UNKNOWN,
    NO_BUSINESS_RULE,
    AttackEvaluation,
    StageEvaluation,
    StrengthEvaluation,
    SummaryEvaluation,
    SupportEvaluation,
)
from .evaluators import (
    CombinedLuckSummaryBuilder,
    DayunAttackEvaluator,
    DayunLuckStageEvaluator,
    DayunLuckStrengthEvaluator,
    DayunLuckSummaryBuilder,
    DayunSupportEvaluator,
    LayeredAttackEvaluator,
    LayeredLuckStageEvaluator,
    LayeredLuckStrengthEvaluator,
    LayeredSupportEvaluator,
    LiunianAttackEvaluator,
    LiunianLuckStageEvaluator,
    LiunianLuckStrengthEvaluator,
    LiunianSupportEvaluator,
    LiuriAttackEvaluator,
    LiuriLuckStageEvaluator,
    LiuriLuckStrengthEvaluator,
    LiuriSupportEvaluator,
    LiushiAttackEvaluator,
    LiushiLuckStageEvaluator,
    LiushiLuckStrengthEvaluator,
    LiushiSupportEvaluator,
    LiuyueAttackEvaluator,
    LiuyueLuckStageEvaluator,
    LiuyueLuckStrengthEvaluator,
    LiuyueSupportEvaluator,
    NullAttackEvaluator,
    NullLuckStageEvaluator,
    NullLuckStrengthEvaluator,
    NullLuckSummaryBuilder,
    NullSupportEvaluator,
)
from .contracts import (
    LuckCycle,
    LuckEvent,
    LuckPeriod,
    LuckResult,
    LuckTimeline,
    timeline_contract,
)
from .exceptions import (
    LuckContextError,
    LuckEngineError,
    LuckPackageLoadError,
    TimelineContractError,
    TimelineRegistryError,
    TimelineValidationError,
)
from .interfaces import (
    AttackEvaluator,
    DayunProvider,
    LiunianProvider,
    LiuriProvider,
    LiushiProvider,
    LiuyueProvider,
    LuckEvaluator,
    LuckStageEvaluator,
    LuckStrengthEvaluator,
    LuckSummaryBuilder,
    SupportEvaluator,
)
from .models import (
    AnnualLuck,
    DailyLuck,
    DayunPeriod,
    HourlyLuck,
    LiunianPeriod,
    LiuriPeriod,
    LiushiPeriod,
    LiuyuePeriod,
    MajorLuckCycle,
    MonthlyLuck,
    NatalChart,
)
from .analysis import (
    ANALYSIS_VERSION,
    ImpactRegistry,
    LuckAnalysisEngine,
    LuckAnalysisResult,
    luck_analysis_contract,
)
from .decision import (
    DECISION_VERSION,
    LuckDecisionEngine,
    LuckDecisionRegistry,
    LuckDecisionResult,
    luck_decision_contract,
)
from .timeline import (
    TIMELINE_VERSION,
    TimelineRegistry,
    construct_timeline,
)
from .pipeline import (
    PIPELINE_VERSION,
    CanonicalLuckPipeline,
    CanonicalLuckResult,
)
from .contracts.luck_contract import luck_pipeline_contract
from .providers import (
    DefaultDayunProvider,
    DefaultLiunianProvider,
    DefaultLiuriProvider,
    DefaultLiushiProvider,
    DefaultLiuyueProvider,
)

__all__ = [
    "LuckEngine",
    "LuckContext",
    "LuckEngineError",
    "LuckContextError",
    "LuckTimeline",
    "LuckCycle",
    "LuckPeriod",
    "LuckEvent",
    "LuckResult",
    "NatalChart",
    "MajorLuckCycle",
    "AnnualLuck",
    "MonthlyLuck",
    "DailyLuck",
    "HourlyLuck",
    "TimelineRegistry",
    "construct_timeline",
    "timeline_contract",
    "TIMELINE_VERSION",
    "LuckAnalysisEngine",
    "LuckAnalysisResult",
    "ImpactRegistry",
    "luck_analysis_contract",
    "ANALYSIS_VERSION",
    "LuckDecisionEngine",
    "LuckDecisionResult",
    "LuckDecisionRegistry",
    "luck_decision_contract",
    "DECISION_VERSION",
    "CanonicalLuckPipeline",
    "CanonicalLuckResult",
    "luck_pipeline_contract",
    "PIPELINE_VERSION",
    "TimelineValidationError",
    "TimelineRegistryError",
    "TimelineContractError",
    "LuckPackageLoadError",
    "DayunProvider",
    "LiunianProvider",
    "LiuyueProvider",
    "LiuriProvider",
    "LiushiProvider",
    "SupportEvaluator",
    "AttackEvaluator",
    "LuckStrengthEvaluator",
    "LuckStageEvaluator",
    "LuckSummaryBuilder",
    "LuckEvaluator",
    "SupportEvaluation",
    "AttackEvaluation",
    "StrengthEvaluation",
    "StageEvaluation",
    "SummaryEvaluation",
    "UNKNOWN",
    "NO_BUSINESS_RULE",
    "DayunPeriod",
    "LiunianPeriod",
    "LiuyuePeriod",
    "LiuriPeriod",
    "LiushiPeriod",
    "DefaultDayunProvider",
    "DefaultLiunianProvider",
    "DefaultLiuyueProvider",
    "DefaultLiuriProvider",
    "DefaultLiushiProvider",
    "NullSupportEvaluator",
    "NullAttackEvaluator",
    "NullLuckStrengthEvaluator",
    "NullLuckStageEvaluator",
    "NullLuckSummaryBuilder",
    "DayunSupportEvaluator",
    "DayunAttackEvaluator",
    "DayunLuckStrengthEvaluator",
    "DayunLuckStageEvaluator",
    "DayunLuckSummaryBuilder",
    "LiunianSupportEvaluator",
    "LiunianAttackEvaluator",
    "LiunianLuckStrengthEvaluator",
    "LiunianLuckStageEvaluator",
    "LiuyueSupportEvaluator",
    "LiuyueAttackEvaluator",
    "LiuyueLuckStrengthEvaluator",
    "LiuyueLuckStageEvaluator",
    "LiuriSupportEvaluator",
    "LiuriAttackEvaluator",
    "LiuriLuckStrengthEvaluator",
    "LiuriLuckStageEvaluator",
    "LiushiSupportEvaluator",
    "LiushiAttackEvaluator",
    "LiushiLuckStrengthEvaluator",
    "LiushiLuckStageEvaluator",
    "LayeredSupportEvaluator",
    "LayeredAttackEvaluator",
    "LayeredLuckStrengthEvaluator",
    "LayeredLuckStageEvaluator",
    "CombinedLuckSummaryBuilder",
]
