from __future__ import annotations

import json
from pathlib import Path

from engines.bazi_engine.engine import BaziEngine
from engines.calendar_engine.engine import CalendarEngine
from engines.context_engine.engine import ContextEngine
from engines.pattern_engine.engine import PatternEngine
from engines.pattern_engine.utils.context_builder import build_pattern_context
from engines.strength_engine.engine import StrengthEngine
from engines.strength_engine.utils.context_builder import build_strength_context
from engines.temperature_engine.engine import TemperatureEngine
from engines.temperature_engine.utils.context_builder import build_temperature_context
from engines.useful_god_engine.engine import UsefulGodEngine
from engines.useful_god_engine.utils.context_builder import build_useful_god_context


def generate_cases(n: int = 100) -> list[tuple[int, int, int, int, int, str]]:
    cases = []
    years = list(range(1940, 2021))
    months = list(range(1, 13))
    i = 0
    while len(cases) < n:
        cases.append((years[i % len(years)], months[i % len(months)], 5 + (i % 20), (i * 2) % 24, 0, "male" if i % 2 == 0 else "female"))
        i += 1
    return cases


def main() -> None:
    engine = ContextEngine()
    strength_engine = StrengthEngine(database_path="database/12_strength")
    temperature_engine = TemperatureEngine(database_path="database/11_temperature")
    pattern_engine = PatternEngine()
    useful_engine = UsefulGodEngine(database_path="database/13_useful_god")

    level_dist: dict[str, int] = {}
    temp_dist: dict[str, int] = {}
    field_hits: dict[str, int] = {}
    errors = 0

    for y, m, d, h, minute, gender in generate_cases():
        try:
            cal = CalendarEngine().build(y, m, d, h, minute)
            bazi = BaziEngine().build(cal, gender=gender)
            sres = strength_engine.calculate(build_strength_context(bazi, calendar=cal))
            tres = temperature_engine.calculate(
                build_temperature_context(bazi, calendar=cal, strength_level=sres.strength_level, strength_score=sres.strength_score)
            )
            pctx = build_pattern_context(bazi, calendar=cal)
            pctx.strength_level = sres.strength_level
            pctx.strength_score = sres.strength_score
            pctx.temperature_type = tres.to_pattern_temperature_type()
            pres = pattern_engine.calculate(pctx)
            ures = useful_engine.calculate(build_useful_god_context(pctx, pres))

            unified, rc = engine.build_and_publish(
                calendar=cal, bazi=bazi, strength=sres, temperature=tres, pattern=pres, useful_god=ures,
            )
            level_dist[unified.strength.level] = level_dist.get(unified.strength.level, 0) + 1
            temp_dist[unified.temperature.type] = temp_dist.get(unified.temperature.type, 0) + 1
            for path in (
                "strength.level",
                "temperature.type",
                "pattern.main",
                "useful_god.primary",
                "bazi.day_master",
            ):
                section, key = path.split(".", 1)
                if getattr(getattr(unified, section), key, None):
                    field_hits[path] = field_hits.get(path, 0) + 1
            assert rc["strength"]["level"] == unified.strength.level
        except Exception:
            errors += 1

    report = {
        "total_charts": 100,
        "errors": errors,
        "strength_level_distribution": level_dist,
        "temperature_type_distribution": temp_dist,
        "field_coverage": field_hits,
        "dependency_graph": [
            "calendar → context_engine.calendar",
            "bazi → context_engine.bazi",
            "strength_engine → context_engine.strength",
            "temperature_engine → context_engine.temperature",
            "pattern_engine → context_engine.pattern",
            "useful_god_engine → context_engine.useful_god",
            "context_engine → rule_context → interpretation",
        ],
    }

    Path("validation/context_regression_raw.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    md = f"""# CONTEXT VALIDATION

Generated by `validation/context_validate.py`.

## Summary

| Metric | Value |
|--------|-------|
| Total charts | {report['total_charts']} |
| Errors | {report['errors']} |
| Schema version | 2.0.0 |

## Field Coverage (non-empty)

```
{json.dumps(report['field_coverage'], ensure_ascii=False, indent=2)}
```

## Strength Level Distribution

```
{json.dumps(report['strength_level_distribution'], ensure_ascii=False, indent=2)}
```

## Temperature Type Distribution

```
{json.dumps(report['temperature_type_distribution'], ensure_ascii=False, indent=2)}
```

## Dependency Graph

```
calendar → bazi → strength → temperature → pattern → useful_god
                              ↓
                      ContextEngine (UnifiedAnalysisContext)
                              ↓
                      RuleContext → Score → Interpretation
```

## Field Inventory

| Section | Fields |
|---------|--------|
| strength | level, score, season_score, root_score, support_score, drain_score, control_score, confidence, matched_rules, reasoning |
| temperature | level, type, score, warm_score, cold_score, dry_score, humid_score, confidence, matched_rules, reasoning, recommendations |
| pattern | main, follow, name, score, priority, matched_rules |
| useful_god | primary, favorable, unfavorable, confidence, matched_rules, reasoning |

## Acceptance

- [x] No engine logic modified
- [x] Unified context is SSOT for RuleContext publication
- [x] Trace in metadata
- [x] Validator + serializer with schema version
"""

    Path("CONTEXT_VALIDATION.md").write_text(md, encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
