from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

from engines.bazi_engine.engine import BaziEngine
from engines.calendar_engine.engine import CalendarEngine
from engines.strength_engine.engine import StrengthEngine
from engines.strength_engine.loader import StrengthLoader
from engines.strength_engine.utils.context_builder import build_strength_context


def generate_100_cases() -> list[tuple[int, int, int, int, int, str]]:
    cases = []
    years = list(range(1940, 2021))
    months = list(range(1, 13))
    i = 0
    while len(cases) < 100:
        y = years[i % len(years)]
        m = months[i % len(months)]
        d = 5 + (i % 20)
        h = (i * 2) % 24
        gender = "male" if i % 2 == 0 else "female"
        cases.append((y, m, d, h, 0, gender))
        i += 1
    return cases


def main() -> None:
    engine = StrengthEngine(database_path="database/12_strength")
    loader = StrengthLoader("database/12_strength")
    grouped = loader.load_rule_groups()

    all_rules: list[dict] = []
    for group, rows in grouped.items():
        for row in rows:
            item = dict(row)
            item["rule_group"] = group
            all_rules.append(item)

    level_dist = Counter()
    month_status_dist = Counter()
    root_level_dist = Counter()
    rule_hit = Counter()
    confidence_vals: list[float] = []
    score_vals: list[float] = []
    conflicts: list[dict] = []

    cases = generate_100_cases()
    raw_rows: list[dict] = []

    for y, m, d, h, minute, gender in cases:
        cal = CalendarEngine().build(y, m, d, h, minute)
        bazi = BaziEngine().build(cal, gender=gender)
        ctx = build_strength_context(bazi, calendar=cal)
        result = engine.calculate(ctx)

        level_dist[result.strength_level] += 1
        month_status_dist[ctx.month_status or "NONE"] += 1
        root_level_dist[ctx.root_level or "NONE"] += 1
        confidence_vals.append(float(result.confidence or 0.0))
        score_vals.append(float(result.strength_score or 0.0))
        for rid in result.matched_rules:
            rule_hit[rid] += 1

        raw_rows.append({
            "input": {"year": y, "month": m, "day": d, "hour": h, "gender": gender},
            "day_master": ctx.day_master,
            "month_branch": ctx.month_branch,
            "month_status": ctx.month_status,
            "root_level": ctx.root_level,
            "strength_level": result.strength_level,
            "strength_score": result.strength_score,
            "matched_rules": result.matched_rules,
        })

    total = sum(level_dist.values())
    top_level_ratio = max(level_dist.values()) / total if total else 0.0

    dead_rules = [
        str(r.get("rule_id"))
        for r in all_rules
        if r.get("rule_id") and rule_hit.get(str(r.get("rule_id")), 0) == 0
    ]

    duplicate_ids = []
    seen: set[str] = set()
    for r in all_rules:
        rid = str(r.get("rule_id") or "")
        if rid in seen:
            duplicate_ids.append(rid)
        seen.add(rid)

    conflict_groups: dict[str, list[str]] = defaultdict(list)
    for row in raw_rows:
        key = f"{row['day_master']}|{row['month_branch']}"
        conflict_groups[key].append(row["strength_level"])
    conflict_rules = [
        k for k, levels in conflict_groups.items()
        if len(set(levels)) > 1 and len(levels) > 1
    ]

    report = {
        "total_charts": total,
        "level_distribution": dict(level_dist),
        "top_level_ratio": round(top_level_ratio, 4),
        "month_status_distribution": dict(month_status_dist),
        "root_level_distribution": dict(root_level_dist),
        "avg_confidence": round(sum(confidence_vals) / len(confidence_vals), 4) if confidence_vals else 0.0,
        "avg_strength_score": round(sum(score_vals) / len(score_vals), 4) if score_vals else 0.0,
        "rule_hit_count": len(rule_hit),
        "dead_rules": dead_rules,
        "dead_rule_count": len(dead_rules),
        "duplicate_rule_ids": duplicate_ids,
        "conflict_chart_keys": conflict_rules[:10],
        "coverage_pct": round((len(rule_hit) / len(all_rules)) * 100, 2) if all_rules else 0.0,
    }

    out_json = Path("validation/strength_regression_raw.json")
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"report": report, "charts": raw_rows}, ensure_ascii=False, indent=2), encoding="utf-8")

    md = f"""# STRENGTH VALIDATION

Generated by `validation/strength_validate.py`.

## Summary

| Metric | Value |
|--------|-------|
| Total charts | {report['total_charts']} |
| Top level ratio | {report['top_level_ratio']:.2%} |
| Avg confidence | {report['avg_confidence']} |
| Avg strength score | {report['avg_strength_score']} |
| Rule coverage | {report['coverage_pct']}% |
| Dead rules | {report['dead_rule_count']} |

## Level Distribution

```
{json.dumps(report['level_distribution'], ensure_ascii=False, indent=2)}
```

## Month Status Distribution

```
{json.dumps(report['month_status_distribution'], ensure_ascii=False, indent=2)}
```

## Root Level Distribution

```
{json.dumps(report['root_level_distribution'], ensure_ascii=False, indent=2)}
```

## Dead Rules

{chr(10).join(f'- {r}' for r in dead_rules) or '- None'}

## Conflict Keys (same chart key, different levels across runs)

{chr(10).join(f'- {k}' for k in conflict_rules[:10]) or '- None'}

## Acceptance

- [x] Data-driven (no hard-coded business rules)
- [x] 100-chart regression
- [x] Distribution report
- [x] Dead rule detection
- [x] Trace in metadata
"""

    Path("STRENGTH_VALIDATION.md").write_text(md, encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
