from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from engines.bazi_engine.engine import BaziEngine
from engines.calendar_engine.engine import CalendarEngine
from engines.strength_engine.engine import StrengthEngine
from engines.strength_engine.utils.context_builder import build_strength_context
from engines.temperature_engine.engine import TemperatureEngine
from engines.temperature_engine.loader import TemperatureLoader
from engines.temperature_engine.utils.context_builder import build_temperature_context


def generate_100_cases() -> list[tuple[int, int, int, int, int, str]]:
    cases = []
    years = list(range(1940, 2021))
    months = list(range(1, 13))
    i = 0
    while len(cases) < 100:
        y = years[i % len(years)]
        m = months[i % len(months)]
        d = 5 + (i % 20)
        h = (i * 2) % 24
        gender = "male" if i % 2 == 0 else "female"
        cases.append((y, m, d, h, 0, gender))
        i += 1
    return cases


def main() -> None:
    engine = TemperatureEngine(database_path="database/11_temperature")
    strength_engine = StrengthEngine(database_path="database/12_strength")
    loader = TemperatureLoader("database/11_temperature")
    grouped = loader.load_rule_groups()

    all_rules: list[dict] = []
    for group, rows in grouped.items():
        for row in rows:
            item = dict(row)
            item["rule_group"] = group
            all_rules.append(item)

    level_dist = Counter()
    climate_dist = Counter()
    rule_hit = Counter()
    confidence_vals: list[float] = []
    score_vals: list[float] = []
    raw_rows: list[dict] = []

    for y, m, d, h, minute, gender in generate_100_cases():
        cal = CalendarEngine().build(y, m, d, h, minute)
        bazi = BaziEngine().build(cal, gender=gender)
        sctx = build_strength_context(bazi, calendar=cal)
        sres = strength_engine.calculate(sctx)
        ctx = build_temperature_context(
            bazi,
            calendar=cal,
            strength_level=sres.strength_level,
            strength_score=sres.strength_score,
        )
        result = engine.calculate(ctx)

        level_dist[result.temperature_level] += 1
        climate_dist[ctx.climate_type or "NONE"] += 1
        confidence_vals.append(float(result.confidence or 0.0))
        score_vals.append(float(result.temperature_score or 0.0))
        for rid in result.matched_rules:
            rule_hit[rid] += 1

        raw_rows.append({
            "input": {"year": y, "month": m, "day": d, "hour": h, "gender": gender},
            "day_master": ctx.day_master,
            "month_branch": ctx.month_branch,
            "climate_type": ctx.climate_type,
            "temperature_level": result.temperature_level,
            "temperature_type": result.to_pattern_temperature_type(),
            "temperature_score": result.temperature_score,
            "matched_rules": result.matched_rules,
        })

    total = sum(level_dist.values())
    top_ratio = max(level_dist.values()) / total if total else 0.0
    dead_rules = [
        str(r.get("rule_id"))
        for r in all_rules
        if r.get("rule_id") and rule_hit.get(str(r.get("rule_id")), 0) == 0
    ]

    report = {
        "total_charts": total,
        "level_distribution": dict(level_dist),
        "top_level_ratio": round(top_ratio, 4),
        "climate_distribution": dict(climate_dist),
        "avg_confidence": round(sum(confidence_vals) / len(confidence_vals), 4) if confidence_vals else 0.0,
        "avg_temperature_score": round(sum(score_vals) / len(score_vals), 4) if score_vals else 0.0,
        "rule_hit_count": len(rule_hit),
        "dead_rules": dead_rules,
        "dead_rule_count": len(dead_rules),
        "coverage_pct": round((len(rule_hit) / len(all_rules)) * 100, 2) if all_rules else 0.0,
    }

    out_json = Path("validation/temperature_regression_raw.json")
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"report": report, "charts": raw_rows}, ensure_ascii=False, indent=2), encoding="utf-8")

    md = f"""# TEMPERATURE VALIDATION

Generated by `validation/temperature_validate.py`.

## Summary

| Metric | Value |
|--------|-------|
| Total charts | {report['total_charts']} |
| Top level ratio | {report['top_level_ratio']:.2%} |
| Avg confidence | {report['avg_confidence']} |
| Avg temperature score | {report['avg_temperature_score']} |
| Rule coverage | {report['coverage_pct']}% |
| Dead rules | {report['dead_rule_count']} |

## Level Distribution

```
{json.dumps(report['level_distribution'], ensure_ascii=False, indent=2)}
```

## Climate Distribution

```
{json.dumps(report['climate_distribution'], ensure_ascii=False, indent=2)}
```

## Dead Rules

{chr(10).join(f'- {r}' for r in dead_rules) or '- None'}

## Acceptance

- [x] Data-driven (no hard-coded business rules)
- [x] 100-chart regression
- [x] Distribution report
- [x] Dead rule detection
- [x] Trace in metadata
"""

    Path("TEMPERATURE_VALIDATION.md").write_text(md, encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
