/**
 * UI-17 Print Experience System. Print consumer only. Presentation copy unchanged.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { cleanup, render } from "@testing-library/react";
import { ExecutiveReportPage } from "../../src/screens/executive_report";
import type { AnalysisDataDto, AnalyzeChartRequest } from "../../src/models";

const HERE = dirname(fileURLToPath(import.meta.url));
const PORTAL = resolve(HERE, "../..");
const REPO = resolve(PORTAL, "../..");
const PRINT_DIR = resolve(PORTAL, "src/screens/executive_report/print");
const PAGE_SRC = readFileSync(resolve(PORTAL, "src/screens/executive_report/ExecutiveReportPage.tsx"), "utf8");
const MODEL_SRC = readFileSync(resolve(PORTAL, "src/screens/executive_report/reportModel.ts"), "utf8");
const PRINT_CSS = readFileSync(resolve(PRINT_DIR, "print.css"), "utf8");
const APP_PY = readFileSync(resolve(PORTAL, "app.py"), "utf8");

const PRESENTATION = JSON.parse(
  readFileSync(resolve(REPO, "implementation/narrative_v2/n_imp_09a/case0001_presentation_v2_1.json"), "utf8"),
) as Record<string, unknown>;

const CONSULTING = (PRESENTATION.interpretation as { consulting_flow: string }).consulting_flow;
const HEADLINE = (PRESENTATION.overview as { headline: string }).headline;
const SUMMARY = (PRESENTATION.overview as { summary: string }).summary;
const PRIORITY = (PRESENTATION.action_plan as { top_priority: { title: string } }).top_priority.title;

const REQUEST: AnalyzeChartRequest = {
  year: 1987,
  month: 1,
  day: 21,
  hour: 4,
  minute: 30,
  gender: "male",
  full_name: "Nguyễn Tiến Sơn",
  birth_place: "Hà Tây, Việt Nam",
};

const ANALYSIS = {
  analysis_id: "ana-secret-debug-id",
  identity: {
    person: {
      full_name: "Nguyễn Tiến Sơn",
      gender: "male",
      solar_birth: "1987-01-21",
      birth_time: "04:30",
      birth_place: "Hà Tây, Việt Nam",
    },
  },
  result_meta: {
    created_at: "2026-08-30T09:15:00Z",
    release_label: "BTE V1.0",
  },
  bazi: {
    day_master: "Canh",
    year_pillar: { stem: "Bính", branch: "Dần", ten_god: "Thiên Ấn" },
    month_pillar: { stem: "Tân", branch: "Sửu", ten_god: "Chính Ấn" },
    day_pillar: { stem: "Canh", branch: "Ngọ", ten_god: "Nhật Chủ" },
    hour_pillar: { stem: "Mậu", branch: "Dần", ten_god: "Thương Quan" },
  },
  five_elements: { counts: { wood: 4, fire: 5, earth: 6, metal: 3, water: 1 } },
  strength: { strength_level: "strong" },
  pattern: { cach_cuc: "Chính Ấn", formation: ["Ấn tinh tọa tháng"] },
  luck: {
    direction_label: "Thuận",
    start_age: 5,
    current_cycle: { index: 3, gan_zhi: "Ất Tỵ", year_start: 2022, year_end: 2031 },
    cycles: [
      { index: 3, gan_zhi: "Ất Tỵ", year_start: 2022, year_end: 2031 },
      { index: 4, gan_zhi: "Bính Ngọ", year_start: 2032, year_end: 2041 },
    ],
  },
  narrative_v2_shadow: {
    status: "ok",
    presentation: PRESENTATION,
    error: null,
  },
} as AnalysisDataDto;

afterEach(cleanup);

function renderReport() {
  return render(<ExecutiveReportPage analysis={ANALYSIS} request={REQUEST} />);
}

describe("UI-17 print experience", () => {
  it("applies A4 print grid and Print Design System margins", () => {
    expect(PRINT_CSS).toMatch(/size:\s*A4 portrait/);
    expect(PRINT_CSS).toMatch(/margin:\s*20mm 18mm 22mm 18mm/);
    expect(PRINT_CSS).not.toContain("bte-cdash");
    expect(PRINT_CSS).not.toContain("dashboard");
  });

  it("renders running header with title, customer, and version", () => {
    const { container } = renderReport();
    const header = container.querySelector('[data-print="header"]');
    expect(header).toBeTruthy();
    expect(header?.textContent).toContain("Báo cáo luận giải Bát Tự");
    expect(header?.textContent).toContain("Nguyễn Tiến Sơn");
    expect(header?.textContent).toContain("BTE V1.0");
    expect(header?.textContent).not.toContain("ana-secret-debug-id");
  });

  it("renders running footer with Generated by BTE, version, confidential, page marker", () => {
    const { container } = renderReport();
    const footer = container.querySelector('[data-print="footer"]');
    expect(footer).toBeTruthy();
    expect(footer?.textContent).toContain("Generated by BTE");
    expect(footer?.textContent).toContain("BTE V1.0");
    expect(footer?.textContent).toContain("Confidential");
    expect(container.querySelector("[data-print='page-number']")).toBeTruthy();
    expect(PRINT_CSS).toContain("counter(page)");
  });

  it("keeps cover as page 1 and major section page-break rules", () => {
    expect(PRINT_CSS).toContain("page-break-after: always");
    expect(PRINT_CSS).toContain("page-break-before: always");
    expect(PRINT_CSS).toContain("page-break-inside: avoid");
    expect(PRINT_CSS).toContain("orphans: 3");
    expect(PRINT_CSS).toContain("widows: 3");
    const { container } = renderReport();
    expect(container.querySelector('[data-print="cover"]')).toBeTruthy();
    expect(container.querySelector('[data-print-break-before="true"]')).toBeTruthy();
    expect(container.querySelector('[data-print="appendix"]')).toBeTruthy();
  });

  it("uses UI-13 typography with print adjustments only", () => {
    expect(PRINT_CSS).toContain("font-size: 10pt");
    expect(PRINT_CSS).toContain("font-size: 14pt");
    expect(PRINT_CSS).toContain("font-size: 26pt");
    expect(PRINT_CSS).toContain("print-color-adjust: exact");
  });

  it("limits print callouts to Executive Summary and Top Priority", () => {
    const { container } = renderReport();
    const callouts = [...container.querySelectorAll("[data-print-callout]")].map((node) =>
      node.getAttribute("data-print-callout"),
    );
    expect(callouts).toEqual(["insight", "priority"]);
  });

  it("renders consulting_flow and action wording unchanged", () => {
    const { container } = renderReport();
    expect(container.querySelector("[data-consulting-flow]")?.textContent).toBe(CONSULTING);
    expect(container.querySelector("[data-report-overview='headline']")?.textContent).toBe(HEADLINE);
    expect(container.querySelector("[data-report-overview='summary']")?.textContent).toBe(SUMMARY);
    expect(container.querySelector("[data-action-priority-title]")?.textContent).toBe(PRIORITY);
  });

  it("does not compose Narrative or change Presentation or Export", () => {
    expect(MODEL_SRC).toContain("adaptNarrativeV2Presentation");
    expect(MODEL_SRC).not.toContain("selectNarrativePresentation");
    expect(PAGE_SRC).not.toContain("fullReportViewModel");
    expect(PAGE_SRC).not.toMatch(/engines\./);
    expect(APP_PY).toMatch(/return page\("reports", "reports\.html"\)/);
    expect(renderReport().container.querySelector("[data-pdf-export]")?.getAttribute("data-pdf-export")).toBe(
      "false",
    );
    expect(renderReport().container.querySelector("[data-print-ready]")?.getAttribute("data-print-ready")).toBe(
      "true",
    );
  });

  it("keeps visualization labels so print remains readable without color", () => {
    const { container } = renderReport();
    expect(container.querySelector(".bte-er__bar-name")?.textContent).toBeTruthy();
    expect(container.querySelector(".bte-er__bar-count")?.textContent).toBeTruthy();
    expect(PRINT_CSS).toContain(".bte-er__bar-fill");
    expect(PRINT_CSS).toContain("border: 0.4pt solid currentColor");
  });

  it("includes archive signature without internal ids", () => {
    const { container } = renderReport();
    const signature = container.querySelector('[data-print="signature"]');
    expect(signature?.textContent).toContain("Prepared by");
    expect(signature?.textContent).toContain("BTE Platform");
    expect(signature?.textContent).toContain("bte.presentation.v2.1");
    expect(signature?.textContent).not.toContain("ana-secret-debug-id");
    expect(signature?.textContent).not.toContain("pipeline_trace");
  });
});
