"""INT-02A Narrative Framework — frozen contracts, no runtime engine."""

from .contracts import (
    ANALYTICAL_TOPICS,
    BLOCK_IDS,
    BLOCK_TITLES_VI,
    COMPOSITION_STAGES,
    CONTRACT_ID,
    FRAMEWORK_VERSION,
    INSUFFICIENT_COPY,
    NARRATIVE_BLOCKS,
    SENTENCE_OWNERS,
    TEMPLATE_HIERARCHY,
    WORKSPACE_BLOCK_ALIASES,
    narrative_framework_contract,
)
from .evidence_item import (
    CLASSIFICATION_NEGATIVE,
    CLASSIFICATION_NEUTRAL,
    CLASSIFICATION_POSITIVE,
    EVIDENCE_CLASSIFICATIONS,
    NarrativeEvidenceItem,
)
from .exceptions import NarrativeFrameworkError
from .models import (
    NarrativeBlock,
    NarrativeSentence,
    TopicEvidencePack,
    TopicNarrativeUnit,
)
from .strength import (
    StrengthEvidence,
    StrengthNarrativeEvidencePack,
    StrengthNarrativeUnit,
    bind_strength_evidence,
    classify_strength_evidence,
    compose_strength_narrative,
)
from .useful_god import (
    UsefulGodEvidence,
    UsefulGodNarrativeEvidencePack,
    UsefulGodNarrativeUnit,
    bind_useful_god_evidence,
    classify_useful_god_evidence,
    compose_useful_god_narrative,
)
from .pattern import (
    PatternEvidence,
    PatternNarrativeEvidencePack,
    PatternNarrativeUnit,
    bind_pattern_evidence,
    classify_pattern_evidence,
    compose_pattern_narrative,
)

__all__ = [
    "ANALYTICAL_TOPICS",
    "BLOCK_IDS",
    "BLOCK_TITLES_VI",
    "COMPOSITION_STAGES",
    "CONTRACT_ID",
    "FRAMEWORK_VERSION",
    "INSUFFICIENT_COPY",
    "NARRATIVE_BLOCKS",
    "SENTENCE_OWNERS",
    "TEMPLATE_HIERARCHY",
    "WORKSPACE_BLOCK_ALIASES",
    "NarrativeBlock",
    "NarrativeFrameworkError",
    "NarrativeEvidenceItem",
    "CLASSIFICATION_POSITIVE",
    "CLASSIFICATION_NEUTRAL",
    "CLASSIFICATION_NEGATIVE",
    "EVIDENCE_CLASSIFICATIONS",
    "NarrativeSentence",
    "TopicEvidencePack",
    "TopicNarrativeUnit",
    "StrengthEvidence",
    "StrengthNarrativeEvidencePack",
    "StrengthNarrativeUnit",
    "bind_strength_evidence",
    "classify_strength_evidence",
    "compose_strength_narrative",
    "UsefulGodEvidence",
    "UsefulGodNarrativeEvidencePack",
    "UsefulGodNarrativeUnit",
    "bind_useful_god_evidence",
    "classify_useful_god_evidence",
    "compose_useful_god_narrative",
    "PatternEvidence",
    "PatternNarrativeEvidencePack",
    "PatternNarrativeUnit",
    "bind_pattern_evidence",
    "classify_pattern_evidence",
    "compose_pattern_narrative",
    "narrative_framework_contract",
]
